### PR TITLE
Logo Files

### PR DESCRIPTION
**Pull request by gcarlosr**
jelly-beats-banner
jelly-beats-banner02
jelly-beats-32x32px
jelly-beats-32x32px-black
jelly-beats-32x32px-white
jelly-beats-48x48px
jelly-beats-48x48px-black
jelly-beats-48x48px-white
jelly-beats-96x96px
jelly-beats-96x96px-black
jelly-beats-96x96px-white
jelly-beats-512x512px
jelly-beats-512x512px-black
jelly-beats-512x512px-white

### CODE REVIEW

**Comment by gcarlosr** [comment]
perfect I will add the svg you need as soon as possible. I really would like to see it already adjusted to the application.

**Comment by btzr-io** [comment]
@gcarlosr Can you add a note in `readme.md` that says you're the designer of the logo, something like: 
> Logo design by @gcarlosr

**Comment by gcarlosr** [comment]
HI here .svg file brother 
[Jelly-Beats-SVG.zip](https://github.com/btzr-io/jelly-beats/files/2274686/Jelly-Beats-SVG.zip)

**Comment by gcarlosr** [comment]
Brother let me know to my email elwu3y@gmail.com when the logo will be available in the application, I am eager to see it

**Pull request closed without merging**
